FROM python:3.7-alpine AS BUILDER
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
ADD ./requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt
ADD ./ /code/
RUN python manage.py collectstatic --noinput


FROM nginx:1.17.0-alpine
RUN cat /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/conf.d/default.conf
RUN mkdir -p /code/static
COPY /nginx-front-end.conf  /etc/nginx/conf.d/default.conf
COPY  --from=BUILDER /code/static_collect /code/static
EXPOSE 80
