version: '3.4'
x-default: &default
  restart: on-failure
services:
  api:
    <<: *default
    build:
      context: .
      dockerfile: ./Dockerfile-api
    ports:
      - 8000:8000

  front-end:
    <<: *default
    build:
      context: .
      dockerfile: ./Dockerfile-front-end
    ports:
      - 80:80

  db:
    <<: *default
    volumes:
      - type: bind
        source: ./db-data/db-tcstats-api
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    <<: *default
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db:db
