version: '3.4'
x-default: &default
  restart: always

services:
  api:
    <<: *default
    image: matteob99/tcstats-api:latest
    environment:
      - DOCKER=true
    links:
      - db:db

  front-end:
    <<: *default
    image: matteob99/tcstats-front-end:latest
    links:
      - api

  db:
    <<: *default
    image: postgres:11-alpine
    volumes:
      - type: volume
        source: db-tcstats-api
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tcstats
      - POSTGRES_DB=tcstats

volumes:
  db-tcstats-api:
