# Generated by Django 2.2.3 on 2019-07-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('linked_channel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Channel')),
                ('users', models.ManyToManyField(to='stats.User')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(to='stats.User'),
        ),
    ]
