# Generated by Django 2.2.3 on 2019-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190716_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='users',
            field=models.ManyToManyField(through='stats.UserStatus', to='stats.User'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(through='stats.UserStatus', to='stats.User'),
        ),
    ]
